Repository ocp-power-automation/rsct-operator, pull requests merged in 2024-11, with the labels that each got.

#51 Update RSCT operator status
  api/v1alpha1/rsct_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/rsct-operator.clusterserviceversion.yaml
  bundle/manifests/rsct.ibm.com_rscts.yaml
  config/crd/bases/rsct.ibm.com_rscts.yaml
  config/manifests/bases/rsct-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/rsct_controller.go
  internal/controller/status.go
Labels: lgtm, approved, size/L

#63 Add support for multi arch controller
  .github/workflows/build-operator-images.yml
  Dockerfile
  Makefile
  bundle/manifests/rsct-operator.clusterserviceversion.yaml
  config/manifests/bases/rsct-operator.clusterserviceversion.yaml
Labels: size/S, lgtm, approved

#65 Adding default icon for the operator
  bundle/manifests/rsct-operator.clusterserviceversion.yaml
  config/manifests/bases/rsct-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/XS

#66 Remove testing annotations
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: lgtm, approved, size/XS

#67 Fix: Update the node selector to include the amd64 architecture
  bundle/manifests/rsct-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, approved, size/XS
